#!/bin/bash

# 启动风扇服务脚本

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"/..   # move to project root

# 清理旧的 socket 文件
rm -f /tmp/doly_fan_zmq.sock 2>/dev/null || true

# Add SDK lib paths to LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/pi/DOLY-DIY/SDK/lib:/usr/local/lib:/usr/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH

echo "启动 Fan Service..."
echo "Service 将 bind 到: ipc:///tmp/doly_fan_zmq.sock"
echo "Configuration: ../../config/fan_config.txt"
echo ""
echo "按 Ctrl+C 停止服务"
echo ""

# executable generated by cmake remains in build/ subdir
./build/fan_service --console --bus-endpoint ipc:///tmp/doly_fan_zmq.sock -c "../../config/fan_config.txt"
